language: cpp

sudo: true

compiler:
  # Clang not yet qith Qt 5.0
  #- clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - ubuntu-sdk-team
    packages:
      - g++-5
      #- qt5-qmake qtbase5-dev qtdeclarative5-dev 

cache:
  directories:
    - $HOME/.ccache

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev

install:
  # g++-5 on linux
  - if [ "$CXX" = "g++" ]; then export CC="gcc-5"; export CXX="g++-5"; fi

before_script:
  - mkdir -p ${TRAVIS_BUILD_DIR}/build
  - mkdir -p ${TRAVIS_BUILD_DIR}/install
  - cd ${TRAVIS_BUILD_DIR}/build
  - echo -e '\nlinux-g++* {\nQMAKE_CXX = '${CXX}'\nQMAKE_CC = '${CC}'\n}\n' >> ../src/mpvconfigurator.pro

script:
  - env
  - qmake -qt=qt5 -v
  - if [ "$CXX" = "clang++" ]; then qmake -qt=qt5 -spec linux-clang ../src; else qmake -qt=qt5 ../src; fi
  - make
  #- make install
  #- cd ${TRAVIS_BUILD_DIR}/install

